"""Add indexes for frequently queried fields

Revision ID: a88ea4bb6f3b
Revises: 
Create Date: 2026-03-13 17:22:01.401556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88ea4bb6f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_status'), ['status'], unique=False)

    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drives_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_drives_status'), ['status'], unique=False)
        batch_op.drop_column('urgency')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_published_at'), ['published_at'], unique=False)
        batch_op.drop_column('tags')
        batch_op.drop_column('region')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteers_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteers_status'))
        batch_op.drop_index(batch_op.f('ix_volunteers_created_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_news_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_is_verified'))
        batch_op.drop_index(batch_op.f('ix_news_category'))

    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgency', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_drives_status'))
        batch_op.drop_index(batch_op.f('ix_drives_created_at'))

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_status'))
        batch_op.drop_index(batch_op.f('ix_donations_created_at'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    # ### end Alembic commands ###
